Update requirements.txt
removed package due to error in binder compiling:

ERROR: Could not find a version that satisfies the requirement anaconda-anon-usage==0.4.2 (from versions: none)
ERROR: No matching distribution found for anaconda-anon-usage==0.4.2